version: '3.3'
services:
  express-server:
    build: ./server
    image: express-server
    ports:
      - "3000:8081"

  react-client:
    build: ./client
    image: react-client
    ports: 
      - "80:5000"
    depends_on:
      - express-server
  