version: "3"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev

  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
