version: "3"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    stdin_open: true
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  