name: remote ssh command
on:
  push:
    branches: [main]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 13.40.169.202
        username: ec2-user
        key: ${{ secrets.AWS_PEM_KEY }}
        port: 22
        script: |
          cd notes-webapp
          git pull origin master
          docker system prune -a
          docker-compose up --build -d
